checks:
  php: true
filter:
  excluded_paths:
    - vendor/
    - tests/
tools:
  external_code_coverage:
    timeout: 600
  php_code_sniffer: true
  php_mess_detector: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests]
  php_pdepend: true
  php_cpd:
    enabled: true
    excluded_dirs: [vendor, tests]
  sensiolabs_security_checker: true
