language: php
php:
  - 5.4
before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
script:
  - phpunit --configuration tests/Bluz/Tests/phpunit.xml --coverage-text
  # PEAR packages
  - pear channel-discover pear.phpunit.de
  - pear install phpunit/phpcpd
  - pear install phpunit/phploc
  - phpenv rehash
  - mkdir .reports
  # Duplicate code
  - phpcpd --log-pmd .reports/pmd-cpd.xml src/Bluz/
  # Lines of code
  - phploc --log-csv .reports/phploc.csv src/Bluz
